CREATE TABLE sessions (
  id TEXT PRIMARY KEY, platform TEXT NOT NULL, conversation_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE(platform, conversation_id));

CREATE TABLE runs (
  id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES sessions(id),
  inbound_platform TEXT NOT NULL, inbound_message_id TEXT NOT NULL,
  status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL, error TEXT, owner_id TEXT,
  lease_expires_at TIMESTAMPTZ, execution_token BIGINT NOT NULL DEFAULT 1);

CREATE TABLE inbound_messages (
  platform TEXT NOT NULL, message_id TEXT NOT NULL,
  run_id TEXT NOT NULL UNIQUE REFERENCES runs(id), sender_id TEXT NOT NULL,
  metadata_json JSONB NOT NULL, response TEXT, created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(platform, message_id));

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id),
  run_id TEXT NOT NULL REFERENCES runs(id), role TEXT NOT NULL,
  content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX messages_session_idx ON messages(session_id, id);

CREATE TABLE checkpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES runs(id), sequence INTEGER NOT NULL,
  phase TEXT NOT NULL, state_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL, UNIQUE(run_id, sequence));

CREATE TABLE tool_executions (
  run_id TEXT NOT NULL REFERENCES runs(id), call_id TEXT NOT NULL,
  tool_name TEXT NOT NULL, arguments_json JSONB NOT NULL, status TEXT NOT NULL,
  output TEXT, error TEXT, started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ, PRIMARY KEY(run_id, call_id));

CREATE TABLE session_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id), version INTEGER NOT NULL,
  content TEXT NOT NULL,
  through_message_id BIGINT NOT NULL REFERENCES messages(id),
  created_at TIMESTAMPTZ NOT NULL, UNIQUE(session_id, version));
CREATE INDEX session_summaries_session_idx
  ON session_summaries(session_id, version);

CREATE TABLE approvals (
  id TEXT PRIMARY KEY, platform TEXT NOT NULL, conversation_id TEXT NOT NULL,
  sender_id TEXT NOT NULL, message_id TEXT NOT NULL, metadata_json JSONB NOT NULL,
  tool_call_id TEXT NOT NULL, tool_name TEXT NOT NULL,
  tool_input_json JSONB NOT NULL, arguments_hash TEXT NOT NULL,
  continuation_json JSONB NOT NULL, status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
  decided_by TEXT, decided_at TIMESTAMPTZ, error TEXT, resumed_at TIMESTAMPTZ);
CREATE INDEX approvals_status_idx ON approvals(status, resumed_at);

CREATE TABLE approval_events (
  message_id TEXT PRIMARY KEY,
  approval_id TEXT NOT NULL REFERENCES approvals(id),
  created_at TIMESTAMPTZ NOT NULL);

CREATE TABLE approval_links (
  run_id TEXT NOT NULL, tool_call_id TEXT NOT NULL,
  approval_id TEXT NOT NULL UNIQUE REFERENCES approvals(id),
  PRIMARY KEY(run_id, tool_call_id));

CREATE TABLE run_queue (
  run_id TEXT PRIMARY KEY,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  owner_id TEXT, lease_expires_at TIMESTAMPTZ,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX run_queue_available_idx
  ON run_queue(available_at, lease_expires_at);
